default:
    image: continuumio/miniconda3

stages:
    - unit_tests

run-unit-tests:
    stage: unit_tests
    tags:
        - asprunner
    script:
        - cd "$PROJECT_DIR"
        - conda env update -f environment.yml
        - source activate ramanchada
        - conda install flake8 pytest
        - flake8 tests
        - pytest
