default:
    image: continuumio/miniconda3

stages:
    - unit_tests

run-unit-tests:
    stage: unit_tests
    tags:
        - asprunner
    script:
        - cd "$PROJECT_DIR"
        - conda install mamba -n base -c conda-forge
        - mamba env update -f environment.yml
        - source activate ramanchada
        - mamba install flake8 pytest
        - flake8 tests
        - pip install -e app
        - pytest -k 'not postmetadata and not putmetadata'
