name: ramanchada
channels:
  - conda-forge
  - spectrocat
  - default
dependencies:
  - h5py
  - jupyter
  - matplotlib
  - pandas
  - path
  - pip
  - python<3.10
  - scipy
  - seaborn
  - spectrochempy
  - werkzeug==2.0.3
  - jinja2<3.1.0
  - pip:
    - renishawWiRE==0.1.15
    - sklearn
    - spc @ git+https://github.com/glemaitre/spc.git@44b67d49e1e4fe9364e7cbce9a93086037703511
    - specio @ git+https://github.com/paris-saclay-cds/specio.git@2963fd5bf6633e4b37d0a912c3ad0293371f5c7d
    - -e ramanchada
