# Upload python package to conda forge

name: publish_conda

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual input tags' 
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: alchem0x2A/conda-publish-action@master
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'noarch'
