tasks:
  - source: tasks.metadata.read_metadata
    product: 
      data: products/metadata/
#      nb: products/metadata.get.ipynb
    params:
      root_folder: "{{root_folder}}"
      config_input: "{{config_input}}"    

  - source: tasks.api.folders2hsds
    product: 
      data: products/logs/
  #    nb: products/metadata.get.ipynb
    params:
      config_input: "{{config_input}}"
      metadata_root: "products/metadata/"
      ramandb_api: "{{ramandb_api}}"
      hs_username: "{{hs_username}}"
      hs_password: "{{hs_password}}"
      hsds_investigation: "{{hsds_investigation}}"

      

