# dag-level hooks
on_render: hooks.on_render
on_finish: hooks.on_finish
on_failure: hooks.on_failure

tasks:
  - source: native2chada.py
    product:
      nb: output/native2chada.ipynb
      data: "{{folder_chada}}"
      
    params:
      folder_native: "{{folder_native}}"
      force_chada_generation: "{{force_chada_generation}}"

  - source: plotspectra.py
    product:
      nb: output/plotspectra.ipynb
    on_render: hooks.on_render
    on_finish: hooks.on_finish
    on_failure: hooks.on_failure        
    params:
      folder_chada: "{{folder_chada}}"
       
      
  - source: normalise.py
    product:
      nb: output/normalise.ipynb
    on_render: hooks.on_render
    on_finish: hooks.on_finish
    on_failure: hooks.on_failure  
    papermill_params:
      log_output: True        
         
  - source: metadata.py
    product:
      nb: output/metadata.ipynb
      metadata: "{{folder_chada}}/metadata.json"      
    on_render: hooks.on_render
    on_finish: hooks.on_finish
    on_failure: hooks.on_failure  
    papermill_params:
      log_output: True      
    params:
      folder_native: "{{folder_native}}"       